### ISSUE TITLE
Demo data export Issue

### ISSUE THREAD

**Issue by Rahisaiful** [MachoThemes/epsilon-dashboard#1]
Hi,
I am using your epsilon dashboard from portum theme. I am trying to create demo file demo.js to import demo content. But i don't find how to create or export demo.js file. Please help me.
Thanks.

**Comment by cristianraiber** [comment]
HI Raishful,

any way I can see the theme you're working on? 

Cristian.

**Comment by Rahisaiful** [comment]
Hi Cristian,
Thanks for replay. I am using epsilon dashboard and epsilon framework test purpose to know how to work this  framework. It is nice framework. Now i am trying to generate demo.js file but i don't understand how to generate. 
[ibro.zip](https://github.com/MachoThemes/epsilon-dashboard/files/2400237/ibro.zip)

**Comment by cristianraiber** [comment]
@Rahisaiful - I'm afraid there's nothing I can do to help you at this point. The tool we use for demo content exporting won't be made public anytime soon. 

Feel free to build your own though.
